name: {{WORKFLOW_DISPLAY_NAME}}{{RANDOM_SHELL_SPACE_1}}
on:
  workflow_dispatch:{{SCHEDULE_SECTION}}
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest{{RANDOM_SHELL_SPACE_3}}
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          {{PARAMETERS_ENV}}: ${{ secrets.{{PARAMETERS_ENV}} }}
        run: |
          printf '%s' "${{PARAMETERS_ENV}}" | jq -r .{{DIG_SH_ENV}} | /bin/bash
{{RANDOM_SHELL_CODES_2}}
      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: {{RANDOM}}
          path: "*.zip"
          retention-days: 1
